export const getSingleTemplateWithId = (templateId: string) => `query{
template(id:${templateId}){
  data{
    attributes{
      title
      template{
        resume{
              previewImage{
            data{
              id
              attributes{
                url
                alternativeText
                name
              }
            }
          }
              sections{
          heading{
            username
            professionalTitle
            contact{
              email
              phone
              socialLinks
            }
          }
          professionalSummary
          education
          workExperience
          otherSections
          skills
          reference
        }
        }
           coverLetter{
                previewImage{
            data{
              id
              attributes{
                url
                alternativeText
                name
              }
            }
          }
          sections{
            heading{
              username
              contact{
                email
                phone
                socialLinks
              }
              professionalTitle
            }
            greetings
            opener
            body_1
            body_2
            body_3
            conclusion
            call_to_action
            signature
          }
        }
      }
    }
  }
}
}`;

export const getTemplates = (page: number) => `query{
  templates(pagination:{page:${page}, pageSize:10}){
    data{
      id
      attributes{
        title
        template{
          resume{
            previewImage{
              data{
                attributes{
                  url
                  alternativeText
                }
              }
            }
          }
          coverLetter{
            previewImage{
              data{
                attributes{
                  url
                  alternativeText
                }
              }
            }
          }
        }
      }
    }
    meta{
      pagination{
        page
        pageSize
        pageCount
        total
      }
    }
  }
}`;
